version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-cli

    working_directory: ~/project
    steps:
      - checkout

      - run:
          name: Install PHPUnit
          command: |
            composer require phpunit/phpunit:7.5.17 --no-update

      - run:
          name: Run tests
          command: |
            composer update -n --prefer-dist --no-suggest
            php vendor/bin/phpunit